dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - python-dev
      - python-numpy
      - libeigen3-dev
before_script:
      - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
      - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
      - sudo apt-get update
      - sudo apt-get install ros-kinetic-ros-base
      - sudo rosdep init
      - rosdep update
      - source /opt/ros/kinetic/setup.bash
      - sudo apt-get install ros-kinetic-opencv3

# before_script:
#   # install openCV
#   - git clone https://github.com/opencv/opencv.git
#   - cd opencv
#   - mkdir build
#   - cd build
#   - cmake ..
#   - make -j4
#   - sudo make -j4 install
#   - cd ../..

script:

  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - ./build.sh
